### PR TITLE
Activate WaveView#setMaxDropHeight

### PR DESCRIPTION
**Pull request by jmatsu**
Current implementation of WaveView#setMaxDropHeight ignores the changed parameter.
I fixed it and add the UI component which is related with this feature.

I couldn't notice it, sorry.

Relates with #10

### CODE REVIEW

**Comment by amyu** [comment]
Thanks @jmatsu

**Comment by TPeterW** [comment]
Sorry, but seems like the problem persists, at least on the latest build tools and Android Marshmallow.

**Comment by jmatsu** [comment]
@TPeterW Thank you for your comment. 
Would you please create a new issue and write the more information?

*Unfortunately, I don't have the devices which can be upgraded to Marshmallow now.*

**Comment by TPeterW** [comment]
Hi, thank you, I tried it again, turned out it's not Marshmallow specific, I used the library on my phone, the setMaxDropHeight still isn't working.

**Pull request merged**
